### ISSUE TITLE
change the plan titles

### ISSUE THREAD

**Issue by ajayane** [ajayane/makeintheuk#6]
change the plan title from 3m,6m and 1y to 
basic standard and premium, since this is a one off payment.

**the details of the subscriptions plan needs to be updated once we have the information from client** **TODO**

**Comment by madhavms** [comment]
Plan name changed to basic, standard and premium. TODO need to remove plan during from backend tables but wont be reflecting in frontend for now.

<img width="1319" alt="image" src="https://github.com/ajayane/makeintheuk/assets/41428411/fc8fffa1-aead-4b9f-9eef-22e32fd98c01">

**Comment by madhavms** [comment]
Plan names changed to Basic, Standard and Premium. Closing this issue as fixed.
