### ISSUE TITLE
Newsletter signup chnages

### ISSUE THREAD

**Issue by ajayane** [ajayane/makeintheuk#9]
- change the signup for news letter button text to **Signup**/ INVEST in your future today.
- try to use the email address and name if entered, or leave it as blank
- link to same "invest your future today button" which links to subscription page

**Comment by madhavms** [comment]
- change the signup for news letter button text to Signup/ INVEST in your future today:

<img width="382" alt="image" src="https://github.com/ajayane/makeintheuk/assets/41428411/5aabd19c-28ce-4146-9cb7-5dbd2576574a">

- try to use the email address and name if entered, or leave it as blank:

Email address and name are being used to auto populate fields in subscription page.
<img width="1135" alt="image" src="https://github.com/ajayane/makeintheuk/assets/41428411/1ae95371-384a-4a1b-b5d8-9f30a2d13192">

- link to same "invest your future today button" which links to subscription page
Linked to the subscription page

**Comment by madhavms** [comment]
Proposed changes have been implemented.
